### ISSUE TITLE
steam checksum is wrong

### ISSUE THREAD

**Issue by itzonban** [pauby/ChocoPackages#11]
Hi,

'choco install steam' fails with mismatch checksum error. It seems that the steam installer file has changed, I get the following sha256-checksum out of it:

3bc6942fe09f10ed3447bccdcf4a70ed369366fef6b2c7f43b541f1a3c5d1c51

**Comment by itzonban** [comment]
Fixed with version 2.10.91.910301

**Comment by pauby** [comment]
I'm no longer maintaining the steam package so it's been removed from this repo.
