### ISSUE TITLE
(virtualbox-guest-additions-guest.install) failing verification

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [pauby/ChocoPackages#123]
The past three versions ([`6.1.28`](https://community.chocolatey.org/packages/virtualbox-guest-additions-guest.install/6.1.28), [`6.1.30`](https://community.chocolatey.org/packages/virtualbox-guest-additions-guest.install/6.1.30) and [`6.1.32`](https://community.chocolatey.org/packages/virtualbox-guest-additions-guest.install/6.1.32)) have all failed the verifier. Versions .28 and .30 have been rejected due to this.

**Comment by pauby** [comment]
Strangely the latest version, [6.1.34](https://community.chocolatey.org/packages/virtualbox-guest-additions-guest.install/6.1.34#versionhistory) passed Verification....

**Comment by Leif-W** [comment]
Possibly broken again with 6.1.36, crashing on install or upgrade from 6.1.34.

**Comment by pauby** [comment]
I've just seen your comment @Leif-W. Version 6.1.36 has not been pushed so this isn't from the package.
