### ISSUE TITLE
(snagit) Package is not updating

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#127]
There has been a change in how Snagit runs (now needing other Microsoft software) so the package needs to be overhauled.

**Comment by virtualex-itv** [comment]
I have an update ready for your review... I've completely rewritten the package and now it works as expected.  will submit a PR soon...

**Comment by virtualex-itv** [comment]
https://github.com/pauby/ChocoPackages/pull/128

**Comment by pauby** [comment]
@virtualex-itv I've gone through the changes you made to the `snagit` package and there wasn't anything in there that would have changed the behaviour of the update script. 

My assumption was that the update was somehow broken and _assumed_ it was on Elgato's end. The Streamdeck MSI had been broken in the past so I don't have a lot of faith in Elgato getting things right.

However, the update script as it stands right now works when running locally. But it doesn't work in AppVeyor. All that is shown in the logs is `streamdeck has no updates`. 

When you log into the AppVeyor server and run the update script, this is what you get:

```
PS C:\projects\chocopackages\automatic\streamdeck> .\update.ps1
streamdeck - checking updates using capu version 0.1.1
au_GetLatest failed
The remote server returned an error: (403) Forbidden.
At C:\projects\chocopackages\capu\capu.psm1:984 char:9
+         throw "au_GetLatest failed`n$_"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (au_GetLatest fa...403) Forbidden.:String) [], RuntimeException
    + FullyQualifiedErrorId : au_GetLatest failed
The remote server returned an error: (403) Forbidden.

PS C:\projects\chocopackages\automatic\streamdeck> $releases    = 'https://help.elgato.com/hc/en-us/articles/36002824263
1-Elgato-Stream-Deck-Software-Release-Notes'
PS C:\projects\chocopackages\automatic\streamdeck> Invoke-WebRequest -Uri $releases -UseBasicParsing -UserAgent [Microso
ft.PowerShell.Commands.PSUserAgent]::FireFox
Invoke-WebRequest : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Invoke-WebRequest -Uri $releases -UseBasicParsing -UserAgent [Microso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\projects\chocopackages\automatic\streamdeck> Invoke-WebRequest -Uri $releases -UserAgent [Microsoft.PowerShell.Com
mands.PSUserAgent]::FireFox
Invoke-WebRequest : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Invoke-WebRequest -Uri $releases -UserAgent [Microsoft.PowerShell.Com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

The important bit is:

```
The remote server returned an error: (403) Forbidden.
```

Bearing in mind this _used_ to work just fine (the last successful update is 4.7.z) so Elgato have changed _something_. This is going to take a little while longer to figure out.

**Comment by pauby** [comment]
This has been fixed in [this commit](https://github.com/pauby/ChocoPackages/commit/62f6d6d5a7f5a6ba57754fe3f860d0c4f7eb2f86).
