### ISSUE TITLE
Camtasia download URLs

### ISSUE THREAD

**Issue by flcdrg** [pauby/ChocoPackages#14]
Looks like the Camtasia package breaks when new versions come out.

Can you use the links from https://www.techsmith.com/download/oldversions so they stay working?

eg. https://download.techsmith.com/camtasiastudio/enu/1801/camtasia.exe

**Comment by pauby** [comment]
Techsmith have really broken the versioning with this new 2018 release. It's official versioned 2018.x but their old versions list it as 18.x and the download URL also has 18x in there. The EXE uses 18.x versioning as well so I have no idea what the official version is. Until they make up their mind I'm using what's on the releases page.

Anyway, I've updated the package with the new URL and pushed it. Will update here as it makes it way through.

**Comment by pauby** [comment]
Thanks for alerting me to it @flcdrg and giving me that old versions URL (which I had before but could not find for this new version! I've added that as a comment in the chocolateyInstall.ps1 so I don't .... lose it this time :)
