### ISSUE TITLE
(streamdeck) Package outdated 

### ISSUE THREAD

**Issue by sir-harlekin** [pauby/ChocoPackages#142]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

5.3.1.15197

### Download location

https://edge.elgato.com/egc/windows/sd/Stream_Deck_5.3.1.15197.msi

### Package Page

https://community.chocolatey.org/packages/streamdeck

**Comment by virtualex-itv** [comment]
https://github.com/pauby/ChocoPackages/pull/143

**Comment by pauby** [comment]
This was completed at https://github.com/pauby/ChocoPackages/commit/f7c07a6655a1ce07fd9ee4f27f19de6c40cc268d
