### ISSUE TITLE
(teamviewer) Setup was cancelled.

### ISSUE THREAD

**Issue by threechord82** [pauby/ChocoPackages#148]
### Chocolatey Version

1.1.0

### Package Version

15.32.2

### Current Behaviour

I am trying to update/reinstall Teamviewer. However, I keep getting error messages. I have the same problem at work where we have a business license.
Here, too, the error message is the same. 

However, an installation of version 15.31.5 works without any problems. 

### Expected Behaviour

Upgrade teamviewer without any Issue

### Steps To Reproduce

1. Install teamviewer 15.31.5 via chocolatey (with admin privileges)
2. try to upgrade teamviewer via "choco upgrade all"  (also with admin privileges)

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22000.0
- PowerShell Version: 7.2.5 
- Shell: Windows Terminal or any Other Shell
```

### Chocolatey Log

```shell
https://gist.github.com/threechord82/5652c162e544b754de742e88e013e7aa
```

**Comment by pauby** [comment]
Thanks for the issue. I've tried this now and it works without issue:

```
PS C:\Users\WDAGUtilityAccount> choco install teamviewer --version 15.31.5 --ignorechecksum
Chocolatey v1.1.0
Installing the following packages:
teamviewer
By installing, you accept licenses for the packages.
Progress: Downloading teamviewer 15.31.5... 100%

teamviewer v15.31.5 [Approved]
teamviewer package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
WARNING: Ignoring checksums due to feature checksumFiles turned off or option --ignore-checksums set.
Installing teamviewer...
teamviewer has been installed.
  teamviewer may be able to be automatically uninstalled.
 The install of teamviewer was successful.
  Software installed to 'C:\Program Files\TeamViewer'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

However, one thing to note is that no matter which version you select you always get the latest version with the Chocolatey open-source version. So, the version I _actually_ installed was [15.32.3](https://community.chocolatey.org/packages/teamviewer#versionhistory) approved on 26 July. This could be an installer issue that they fixed in this new version. That is assuming of course you're no longer having the issue?

**Comment by pauby** [comment]
Closing due to lack of updates.
