### ISSUE TITLE
(teamviewer) Warn if installing x64 and x86 is already installed

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#149]
### Chocolatey Version

N/A

### Package Version

15.26.4+

### Current Behaviour

Installs the x64 version and leaves the x86 version still installed without letting the user know.

### Expected Behaviour

It would be nice if we could warn the user they have the x86 version installed.

### Steps To Reproduce

On an x64 machine:

1. Install a version of the package before 15.26.4 which installs the x86 version of Teamviewer.
2. Upgrade to the latest version.
3. See that the x64 version is installed and the x86 version is not uninstalled.

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

### Anything else?

There is a [comment on the package page](http://disq.us/p/2qdty26) regarding the new x64 version of Teamviewer that was added in 8e7e264dcd207364903283d057291e6a6575098e. Prior to this the x86 version was installed. The installer doesn't uninstall the x86 version, as _maybe_ it (I say maybe as there may be good reasons to have both).

As mentioned in the comment you need to uninstall the x86 version manually.

What may help is that, when installing the x64 version, we look to see if the x86 version is installed and warn the user that they will have to remove it manually.

**Comment by dieechtenilente** [comment]
Would be fixed in #152

**Comment by Destroy666x** [comment]
I think this should have just kept installing x86 and x64 could have been added as a switch.

There's a checksum error currently too, BTW.

**Comment by pauby** [comment]
Chocolatey will install the x64 version if you are on an x64 platform. It's pretty standard behavoiour for a package that has both an x86 and x64 version. To use the x86 version, use the `--force-x86` switch.

**Comment by Destroy666x** [comment]
I see. Then it's a flaw of choco I assume - this is not installing, this is upgrading. Upgrading should go for the same architecture as the one that was installed. I'll create an issue there if there isn't one already.

Not sure what you mean with `--version` requirement, just standard ignoring of checksums worked, weird that TV team regularly enters wrong checksums as this has happened in the past too.
