### ISSUE TITLE
KeePass KeeAgent changed the plugin name - how to handle this?

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#15]
KeePass KeeAgent changed the plugin name leaving users with both named versions. How to handle this?

**Comment by Karreg** [comment]
Following this comment:

> I was asked if I could handle the issue with the package name changing. I am not keen on arbitrarily removing files from a users system. I am happy to flag up that the other file is there and let the user decide however.

My point of view is that NOT deleting the file will break the app, so it makes no sense, and goes against an update system. All update systems overwrite user files, this is the point of an update. 
Creating multiple files is not working. It may works in the future, depending on the will of keepass developer(s). However it's easier and faster to handle it here.

If you need something more user aware, then I would not advise asking him, but asking for a validation.

As pseudo-code:

```
if `-y` mode
then
    overwrite the file
else
    warn user that the file will be overwritten. does he accept?
    if yes
    then
        overwrite the file
    else
        cancel the update
```

The most important point is not to break the app, so multiple files aren't an option.
The only option left is either to accept the update (and file will be overwritten) or not (and file won't be overwritten). In this case, the file itself is not important, there's no configuration, only a binary. If the user wants to rollback, he can uninstall and install a previous version.

**Comment by pauby** [comment]
> if `-y` mode

I'm not sure I understand how that equates to the package?

> The only option left is either to accept the update (and file will be overwritten) or not (and file won't be overwritten). In this case, the file itself is not important, there's no configuration, only a binary. If the user wants to rollback, he can uninstall and install a previous version.

I agree this is likely the best way forward. As I said I'm not keen on arbitrarily deleting files however the previous package version did create this issue (by renaming the .plgx file) so it's best that we clean it up.

However I am still torn by either deleting the file and not telling the user or letting them make their own choice. I am now swaying to the 'delete the file as we created the mess' side of things.

**Comment by Karreg** [comment]
I think the package knows the -y option, but I don't know how it works.

About the whole thing, I don't see the issue with deleting the file, since it's the point of having an updater system...

**Comment by pauby** [comment]
> I think the package knows the -y option, but I don't know how it works.

The `-y` parameter for `choco.exe` just tells Chocolatey not to promot when running the install scripts. It's not a parameter you can supply to the package.

> About the whole thing, I don't see the issue with deleting the file, since it's the point of having an updater system...

As I said I agree since the previous package version caused the issue. What I'm looking for is opinions on how they want it done (silently, told it's been done, given the option to stop it being done).

**Comment by pauby** [comment]
> Go back to the same file name (the previous one) in the package

That for me is a problem because the ACTUAL name of the plugin IS `KeeAgent.plgx`. The previous version was renaming it to `keepass-plugin-keeagent.plgx` which is what is causing the problem.

So if we simply delete the `keepass-plugin-keeagent.plgx` file if it exists and install the `keeagent.plgx` then that should handle it. Which is basically what you're suggesting just with the new filename / old filename swapped.

I'm happy to leave that in the package going forward as if the old file isn't there it does nothing so no harm done.

**Comment by Karreg** [comment]
:+1:

**Comment by pauby** [comment]
New package version published.
