### ISSUE TITLE
(gh) Package is outdated

### ISSUE THREAD

**Issue by brogers5** [pauby/ChocoPackages#154]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.16.1

### Download location

https://github.com/cli/cli/releases/download/v2.16.1/gh_2.16.1_windows_amd64.msi

### Package Page

https://community.chocolatey.org/packages/gh

**Comment by pauby** [comment]
I'm starting to see this with more and more GitHub packages. It will need converted to the API. Leave it with me and I'll do this later / tomorrow.

**Comment by pauby** [comment]
This was fixed in https://github.com/pauby/ChocoPackages/commit/4a23f7de71349c835410db7b1ab840f87b515fff

New package pushed and in moderation.
