### ISSUE TITLE
https://chocolatey.org/packages/keepass.install

### ISSUE THREAD

**Issue by bcurran3** [pauby/ChocoPackages#17]
keepass.install is missing the foss, cross-platform, and freeware tags from the obligatory tags list:
https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#122-obligatory-tags

**Comment by pauby** [comment]
@bcurran3 Those tags apply to the core team packages.

**Comment by bcurran3** [comment]
Agreed, that's where the info came from. Isn't it a reasonable (and very simple) request to follow their exemplary example? Shouldn't we, as packagers, attempt to make our packages as best we can?

You even referenced these tags at https://github.com/chocolatey/choco/issues/1363#issuecomment-340284700 :) Even though nothing (that I know of) has come of it yet, I assumed these were going into the moderation guidelines as "standard issue."

The tags are a simple enhancement to a future package version.
