### ISSUE TITLE
(wavelink/streamdeck) failing to install

### ISSUE THREAD

**Issue by bosmak** [pauby/ChocoPackages#171]
### Chocolatey Version

1.2.1

### Chocolatey License

None

### Package Version

latest

### Current Behaviour

Package isn't installed and shows msiexec options.

https://imgur.com/RjCQWOX

### Expected Behaviour

The package is installed.

### Steps To Reproduce

1. Run `choco install wavelink/streamdeck`

### Environment

```markdown
- Operating System (run `[System.Environment]::OSVersion.ToString()` in a PowerShell session): Microsoft Windows NT 10.0.22621.0

- PowerShell Version (run `$PSVersionTable` in a PowerShell session):
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/bosmak/59cb89de4a23a6049e758eab118e0ffa
```

### Anything else?

I showed the logs for wavelink but the same happens on streamdeck,.

**Comment by pauby** [comment]
Installs are working fine here in a test Windows 10 virtual machine.

Wavelink:

![Screenshot_20230110_210814](https://user-images.githubusercontent.com/12760779/211663037-23d98b77-bb9c-4fd1-8ac7-98514c8f17d9.png)

Streamdeck:

![image](https://user-images.githubusercontent.com/12760779/211663234-0ee8e4d0-7c7c-41b1-934e-3f4cf4c71910.png)

**Comment by bosmak** [comment]
![image](https://user-images.githubusercontent.com/16576236/211666849-a2db7110-2975-4422-b013-249b5822e88a.png)

**Comment by pauby** [comment]
This isn't something I can troubleshoot and fix as I cannot reproduce it. I will try again tomorrow with a different environment.

**Comment by pauby** [comment]
### New Windows 10 environment (Windows Sandbox).

Wavelink:

![image](https://user-images.githubusercontent.com/12760779/211789181-19a138c3-256c-4c39-be9d-2f4b4c591d6c.png)

Streamdeck:

![image](https://user-images.githubusercontent.com/12760779/211790291-df49506d-b136-4ac3-85bf-4c4f5fb5983f.png)

### Azure Windows 10 VM

Wavelink:

![image](https://user-images.githubusercontent.com/12760779/211792453-41b96589-a8b7-4329-a302-47e461b09a67.png)

Streamdeck:

![image](https://user-images.githubusercontent.com/12760779/211792679-5bb1a610-6f62-401f-95a0-b5ef1f0e14f8.png)

I've tested this on 3 different Windows 10 virtual machines (Windows Sandbox, Windows 10 Vagrant virtual machine and a Windows 10 Azure virtual machine) and I can't find any issues. Unless I can reproduce this there isn't anything I can do.

My suggestion would be to try other MSI installers with Chocolatey and try the [Chocolatey Community support](https://ch0.co/community).

**Comment by bosmak** [comment]
I'm trying to give a proper way to reproduce this issue.

For some reason I it works on a the virtual machine that I installed in the same way as my desktop.

**Comment by bosmak** [comment]
@pauby I was able to reproduce the issue. If the user folder has a space, the install fails.

E.g:

C:/Users/John Doe/ - Fails
C:/Users/JohnDoe/ - Works

**Comment by pauby** [comment]
The package doesn't do anything with file paths so that would be either an installer issue or a Chocolatey CLI one.
