### ISSUE TITLE
Yubico Authenticator (Install)

### ISSUE THREAD

**Issue by kuro68k** [pauby/ChocoPackages#179]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

6.2.0

### Download location

https://github.com/Yubico/yubioath-flutter/releases/tag/6.2.0

### Package Page

https://community.chocolatey.org/packages/yubico-authenticator

**Comment by kuro68k** [comment]
To be notified of new releases, go to the GitHub page (https://github.com/Yubico/yubioath-flutter) and click on Watch -> Custom -> tick "releases".

You will then get a notification every time a new release is available.

**Comment by xlammertink** [comment]
I noticed the same thing. I tried installing it manually and noticed that the automatic update script failed. I fixed this and opened new PR https://github.com/pauby/ChocoPackages/pull/180, hoping that this will ensure updates get picked up again.

In the mean time you can install the latest version manually by building and installing the Chocolatey Automatic Package Updater Module (https://github.com/majkinetor/au) for PowerShell
```
.\build.ps1
.\install.ps1
```
Followed by updating, packaging and installing my version of Pauby's ChocoPackages (https://github.com/xlammertink/ChocoYubicoAuthenticator):
```
cd automatic/yubico-authenticator
.\update.ps1
choco pack
choco install yubico-authenticator.6.2.0.nupkg 
```
