### ISSUE TITLE
(syncthing) Outdated

### ISSUE THREAD

**Issue by MageFroh** [pauby/ChocoPackages#186]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.23.6

### Download location

https://github.com/syncthing/syncthing/releases/tag/v1.23.6

### Package Page

https://community.chocolatey.org/packages/syncthing

**Comment by pauby** [comment]
Thanks for letting me know this was broken. It was data in the release notes text that was the culprit.

This has been fixed at https://github.com/pauby/ChocoPackages/commit/aa0814300d788f254fdae89f744ab98c296b0bfe and has just been pushed to the Chocolatey Community Repository.

**Comment by MageFroh** [comment]
Excellent, thanks for fixing this quickly!
