### ISSUE TITLE
adobedigitaleditions_install

### ISSUE THREAD

**Issue by jpluimers** [pauby/ChocoPackages#187]
(I did some editing as the template is not fully markdown aware thereby breaking some of the entered data)

### Chocolatey Version

2.1.0

### Chocolatey License

None

### Package Version

v4.5.12

### Current Behaviour

The install pops up an AutoHotKey (AHK) error when AHK 2.0.0 or higher is installed (which got released december 2022, see https://github.com/AutoHotkey/AutoHotkey/releases).

![image](https://github.com/pauby/ChocoPackages/assets/2033367/d05064e9-8c25-4a77-93ae-4410c4aaa3a1)

Text:

``` text
150960229.ahk

Error: This line does not contain a recognized action.
Text: #NoEnv
Line: 1
File: C:\Users\jeroenp\AppData\Local\Temp\chocolatey\150960229.ahk
The program will exit.

[Help] [Edit] [Reload] [ExitApp] [Abort]
```

### Expected Behaviour

No AHK script error.

### Steps To Reproduce

In an environment with both `authotkey.install` (which is v1 and installs `autohotkey`) and `autohotkey.portable` (which is v2) installed, install `adobedigitaleditions`.

### Environment

- Operating System (run `[System.Environment]::OSVersion.ToString()` in a PowerShell session): Microsoft Windows NT 10.0.22621.0
- PowerShell Version (run `$PSVersionTable` in a PowerShell session):
```text
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
- Shell: `cmd` (but also fails in `PowerShell`)

### Chocolatey Log

https://gist.github.com/jpluimers/4f8120e2d0318c67c9fd516d9bbca713

### Anything else?

Note that the log is after selecting "Abort" in the error dialog. This results in exitcode 1223 as mentioned in https://github.com/pauby/ChocoPackages/blob/master/automatic/adobedigitaleditions/tools/chocolateyInstall.ps1

---

I know the dependency in https://github.com/pauby/ChocoPackages/blob/master/automatic/adobedigitaleditions/adobedigitaleditions.nuspec refers to https://community.chocolatey.org/packages/autohotkey which is still at version 1.x, but other software now depends on 2.0 which means I have these installed:

``` text
autohotkey v1.1.37.1 is the latest version available based on your source(s).
autohotkey.install v1.1.37.1 is the latest version available based on your source(s).
autohotkey.portable v2.0.4 is the latest version available based on your source(s).
```

Packages:

- https://community.chocolatey.org/packages/autohotkey/1.1.37.1
- https://community.chocolatey.org/packages/autohotkey.install/1.1.37.1
- https://community.chocolatey.org/packages/autohotkey.portable/2.0.4

More and more people will bump into that situation, as AHK v2 will gain usage over time.

AHK v2 has removed `#NoEnv` as it is the default behaviour now: https://www.autohotkey.com/docs/v2/v2-changes.htm

> Removed:
> ...
> - #NoEnv (now default behaviour)

Of course I'd rather like that AHK v2 had transformed `#NoEnv` into a no-operation, but for now AHK erroring is a given.

`#NoEnv` in AHK v1 is to ensure that uninitialised AHK variables are not read from the process environment: https://www.autohotkey.com/docs/v1/lib/_NoEnv.htm

> Specifying the line [#NoEnv](https://www.autohotkey.com/docs/v1/lib/_NoEnv.htm) anywhere in a script prevents empty variables from being looked up as potential environment variables.

Looking at https://github.com/pauby/ChocoPackages/blob/master/automatic/adobedigitaleditions/tools/adobedigitaleditions_install.ahk, I see these variables being used: `%A_ScriptDir%` and `%winTitle%`.  
The script itself initialises `%winTitle%` and `%A_ScriptDir%` is predefined by AHK (see https://www.autohotkey.com/docs/v1/Variables.htm#ScriptDir and https://www.autohotkey.com/docs/v2/Variables.htm#ScriptDir).

Since the script is very short and has no uninitialised variables, the first line `#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.` has no performance meaning.  
Now that "compatibility with future AutoHotkey releases" actually means breaking in AHK v2 the line should be removed completely.

**Comment by pauby** [comment]
There is a [PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2246) that I created that adds a v2 for the `autohotkey.install` package (but keeps v1 compatibility) but it hasn't been picked up yet.
