### ISSUE TITLE
(keepass-plugin-keepasshttp) Update the package

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#190]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

Unknown

### Package Page

https://community.chocolatey.org/packages/keepass-plugin-keepasshttp

See https://github.com/chocolatey-community/chocolatey-package-requests/issues/1209. Note that `dtgm` is currently the maintainer, and a PR should be made to remove it from that repository.

**Comment by jeansagi** [comment]
Hi,

Any _news_ about this?


J.

**Comment by pauby** [comment]
As mentioned over on the [Chocolatey Package Request repository](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1209#issuecomment-1987266658), I came to update the package and found that the [latest version is 1.8.4.2](https://github.com/pfn/keepasshttp/tags), which is the same as what is on the [Chocolatey Community Repository](https://community.chocolatey.org/packages/keepass-plugin-keepasshttp). The [last version was released in 2017](https://github.com/pfn/keepasshttp/tags), so I don't see any new versions being released in the future.

As there is nothing to do here, I'll close the issue here and the issue over on my repository.

**Comment by pauby** [comment]
Reopening this. The latest version is 1.8.4.2, but the checksum does not match that which is in the package. Need to look at this and perhaps embed the plugin if the license allows.
