### ISSUE TITLE
(webview2-runtime) Use offline installer 

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#195]
### issue-details

The `webview2-runtime` package uses the web installer to install the software. I had looked into using this for the package, but I was unable to determine the version / URL for downloading (I can't remember the specifics, but I do remember looking at it).

A user contacted me to say that they used a product called [NeverRed](https://www.deyda.net/index.php/en/neverred/) that can download updates for applications and Webview2 Runtime offline installer, is one of those. So we may be able to use the mechanism they use.

**Comment by dandudley** [comment]
Hi Paul, after reviewing the code for NeverRed, it looks like that hooks into Evergreen https://stealthpuppy.com/evergreen/, this is another PowerShell module that is used to download the latest versions of apps from their respective URL's.

https://stealthpuppy.com/apptracker/#microsoftedgewebview2runtime, if you view the apptracker, it shows the latest version of Webview2 and their corresponding URL's based on architecture.

If we look at a small snippet of the NeverRed code below, we can see it uses Get-EvergreenApp:

If ($MSEdgeWebView2 -eq 1) {
        $Product = "Microsoft Edge WebView2"
        $EdgeWebView2D = Get-EvergreenApp -Name MicrosoftEdgeWebView2Runtime | Where-Object { $_.Architecture -eq "$MSEdgeWebView2ArchitectureClear" }
        $Version = $EdgeWebView2D.Version

**Comment by pauby** [comment]
I've [updated `webview2-runtime` to now use the offline installer and used Evergreen](https://github.com/pauby/ChocoPackages/commit/b476881b72f6f91eb72961a217b749517815015f) to do it! Thanks for pointing that out to me. I think it will be very useful in the future!

The update will occur in the new release of `webview2-runtime`.
