### ISSUE TITLE
(adobereader) Desktop icon is being added by default when it should not be

### ISSUE THREAD

**Issue by zippydan** [pauby/ChocoPackages#196]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

2023.6.20320

### Current Behaviour

adobereader install is adding a desktop icon, even though the package description specifically says this is not the default behavior.

### Expected Behaviour

adobereader should not add a desktop icon, or should at least have an argument to not add a desktop icon.

### Steps To Reproduce

Run the choco install for adobereader and watch the Adobe Reader desktop icon appear on your desktop.

### Environment

```markdown
PS C:\Windows\system32> [System.Environment]::OSVersion.ToString()
Microsoft Windows NT 10.0.19045.0
PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Chocolatey Log

```shell
n/a
```

### Anything else?

n/a

**Comment by pauby** [comment]
According to the [code](https://github.com/pauby/ChocoPackages/blob/master/automatic/adobereader/tools/chocolateyinstall.ps1#L110-L114) and the [Adobe docs](https://www.adobe.com/devnet-docs/acrobatetk/tools/AdminGuide/properties.html#command-line-example), `DISABLEDESKTOPSHORTCUT=1` should stop a desktop icon from being created.

When installing the package, this is what I see in the logs:

```
2023-09-14 17:33:11,665 4384 [DEBUG] - Running Install-ChocolateyInstallPackage -silentArgs '/sAll /msi /norestart /quiet PATCH="C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\AcroRdrDCx64Upd2300620320_MUI.msp" ALLUSERS=1 EULA_ACCEPT=YES  DISABLEDESKTOPSHORTCUT=1 DISABLE_ARM_SERVICE_INSTALL=1 UPDATE_MODE=0 /L*v "C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\adobereader.2023.6.20320.Install.log"' -file 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\AcroRdrDCx642300120093_MUI.exe' -fileType 'EXE' -validExitCodes '0 1000 1101 1603' -packageName 'adobereader (installer)' 
...
2023-09-14 17:33:11,743 4384 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -validExitCodes '0 1000 1101 1603' -workingDirectory 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey' -statements '/sAll /msi /norestart /quiet PATCH="C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\AcroRdrDCx64Upd2300620320_MUI.msp" ALLUSERS=1 EULA_ACCEPT=YES  DISABLEDESKTOPSHORTCUT=1 DISABLE_ARM_SERVICE_INSTALL=1 UPDATE_MODE=0 /L*v "C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\adobereader.2023.6.20320.Install.log" ' -exeToRun 'C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\AcroRdrDCx642300120093_MUI.exe' 
```

In my testing, a desktop shortcut is being created so this, from what I can see, is an installer issue and not a package one. Perhaps the installer is broken (again).

![image](https://github.com/pauby/ChocoPackages/assets/12760779/cf4852c2-c0ba-4b85-938a-2ef306b8f98e)

There isn't anything that I can do from a package perspective unless my understanding of the code and docs are incorrect.

**Comment by zippydan** [comment]
I appreciate the quick response and I accept it is an installer issue.  Most likely is either:

- Adobe screwed up (accidentally disabled the switch functionality)
- Intentionally removed the switch functionality (and didn't update their docs)
- Changed the switch functionality, maybe by changing the switch name (and didn't update their docs)

I reported this in case there was an update by Adobe that you had missed.  Thanks for looking anyway.

**Comment by zippydan** [comment]
Should I close this or wait until it is resolved by Adobe?  At least if other people have the same problem they can find this report and the "resolution"?

**Comment by pauby** [comment]
The desktop icon doesn't appear until the 'Applying patch.' text appears. I wonder if it's ignoring the command line.

I installed version 2023.3.20269 (from early August) and it has the same issue. The Adobe specific update logs and the install logs (which are 7MB and 5MB respectively so I won't post them here) show that `DISABLEDESKTOPSHORTCUT=1`. So it's getting through. 

> I reported this in case there was an update by Adobe that you had missed. Thanks for looking anyway

There very well could be. Adobe broke their installer not so long ago, which is why I now maintain the package. So it's maybe an Adobe thing. And that's all I've got to go on just now.

Maybe report it to Adobe?

**Comment by pauby** [comment]
> Should I close this or wait until it is resolved by Adobe? At least if other people have the same problem they can find this report and the "resolution"?

As there isn't anything _I_ can do, I would prefer to close it. People searching can find it under closed issues.

I'll wait for your response before doing so.

**Comment by zippydan** [comment]
"Close as completed" or "Close as not planned"?

**Comment by pauby** [comment]
I'll close it as 'no planned' just now.
