### ISSUE TITLE
(adobereader) Not installing due to more than one installation detected

### ISSUE THREAD

**Issue by githubomane** [pauby/ChocoPackages#197]
### Chocolatey Version

Current 

### Chocolatey License

None

### Package Version

Not sure, first noticed 2 months ago

### Current Behaviour

Since about 2 months ago I can't update Adobe Reader DC because it keeps detecting an old version of Adobe Acrobat (not the reader) I bought years ago and am still using for PDF-editing. 

### Expected Behaviour

Being able to install/update adobereader through chocolatey without having to uninstall my older Adobe Acrobat version 

### Steps To Reproduce

1. Install an Adobe Acrobat version older than Adobe Reader DC
2. Try updating the adobereader package installed using chocolatey 

### Environment

```markdown
- Operating System: Windows 10
```

### Chocolatey Log

```shell
WARNING: 2 matching installs of Adobe Acrobat Reader DC found!
WARNING: To prevent accidental data loss, this install will be aborted.
WARNING: The following installs were found:
WARNING: - Adobe Acrobat X Pro - English, Français, Deutsch 10.1.16
WARNING: - Adobe Acrobat (64-bit) 23.003.20244
ERROR: Installation halted.
The upgrade of adobereader was NOT successful.
```

### Anything else?

I'm currently on mobile, if relevant I'll add version info etc.

**Comment by pauby** [comment]
> WARNING: - Adobe Acrobat X Pro - English, Français, Deutsch 10.1.16
> WARNING: - Adobe Acrobat (64-bit) 23.003.20244

This is the problem. You have Adobe Acrobat X Pro and Adobe Acrobat installed. This is highlighted as an issue and will not proceed:

> WARNING: To prevent accidental data loss, this install will be aborted.

As the package looks for anything installed that matches 'Adobe Acrobat*' it will not proceed if it finds more than one. There is anything I can do about that, unfortunately.

**Comment by githubomane** [comment]
Thanks for your quick reply and also for maintaining the package!

Isn't it possible to add a variable which skips that check? I can install Adobe Reader DC in parallel manually without a problem.

I need the old Acrobat version for editing PDFs, but don't want to use it for general PDF reading because it doesn't receive security updates anymore. That's why I need the Adobe Reader DC too.

**Comment by pauby** [comment]
I could add a switch to bypass it I think (I'd have to dig into it more). But anything I add will only apply to later versions of course. The reason I mention that is you said you want old versions? Or did I misunderstand?

**Comment by githubomane** [comment]
I want to use my old version of Adobe Acrobat Pro, which I bought years ago, for editing PDF files - this version is long out of service and doesn't get  updates anymore. But it is capable of editing PDFs.

I want to use the most recent Adobe Reader DC (free) for reading PDFs, because it's more secure, as it gets updated. I can't use it for editing PDFs, as I don't have a subscription for that.

I just need chocolatey to work for my Adobe reader DC version, so I get updates, and ignore my old Acrobat Pro installation. 

Hope that clarifys things!

**Comment by pauby** [comment]
That makes sense, thanks.

Just to set expectations, I'm unsure when I'll be able to look at this but will do so as soon as I can.

**Comment by githubomane** [comment]
Thanks for looking into it at all! This is definitely not a pressing issue 😀

**Comment by pauby** [comment]
Ignore the above from the bot. Issue has been pinned.

**Comment by pauby** [comment]
This has been added at https://github.com/pauby/ChocoPackages/commit/79f3c035a8c74e8051cdcb5342c7242ccaf8770c and the next version of `adobereader` will support it.
