### ISSUE TITLE
(keepass-plugin-readablepassphrasegen) Outdated

### ISSUE THREAD

**Issue by BubiBalboa** [pauby/ChocoPackages#206]
### Checklist

- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.4.0

### Download location

https://github.com/ligos/readablepassphrasegenerator/releases/tag/release-1.4.0

### Package Page

https://chocolatey.org/packages/keepass-plugin-readablepassphrasegen

**Comment by pauby** [comment]
This is fixed at https://github.com/pauby/ChocoPackages/commit/c3f54adb4e2fbb750aef223283a32a8b076f176a.

Version 1.4.0 of the package had already been pushed but failed validation and was ultimately rejected. Once that has been put back into the 'submitted' state, I will push a new, fixed, version.

**Comment by pauby** [comment]
Version 1.4.0 has been pushed.

**Comment by pauby** [comment]
This has now been approved.
