### ISSUE TITLE
microsoft-vclibs-140-00

### ISSUE THREAD

**Issue by bilach** [pauby/ChocoPackages#207]
### Chocolatey Version

v2.2.2

### Chocolatey License

None

### Package Version

14.0.30704.0

### Current Behaviour

Error - hashes do not match. Actual value was 'A7FB9D76E07B36D868179EB53FFD13740C25242176FA363F154798CF34EDD4A9'.
ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\Microsoft.VCLibs.x86.14.00.Desktop.appx' did not meet '3195DB914BEA1534EE73582CD483C548A929AED2799D305B3BBF7411BA7A6C7D' for checksum type 'SHA256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of microsoft-vclibs-140-00 was NOT successful.

### Steps To Reproduce

1. A clean windows where microsoft-vclibs-140-00 is not installed
2. choco install microsoft-vclibs-140-00

### Environment

```markdown
- Operating System Microsoft Windows Server 2022 10.0.20348
- PowerShell (2.232.1)
```

### Chocolatey Log

```shell
Don't have any.
```

### Anything else?

I downloaded
Microsoft.VCLibs.x86.14.00.Desktop.appx A7FB9D76E07B36D868179EB53FFD13740C25242176FA363F154798CF34EDD4A9
Microsoft.VCLibs.x64.14.00.Desktop.appx B56A9101F706F9D95F815F5B7FA6EFBAC972E86573D378B96A07CFF5540C5961
and they have different checksums than the ones listed here
https://github.com/pauby/ChocoPackages/blob/1a0b5fe548641b60b6f9d6d991fa212ae9954d1a/manual/microsoft-vclibs-140-00/tools/chocolateyInstall.ps1#L67

**Comment by pauby** [comment]
This is fixed for [`microsoft-vclibs-140-00`](https://github.com/pauby/ChocoPackages/commit/dbdb353ebcd1fbda409c7b09c52e7129e83c64e2) and [`microsoft-vclibs`](https://github.com/pauby/ChocoPackages/commit/f8e6fb318b2c48a73a39e59e95d9fcae03ba8613).

Both packages have been pushed and are going through the moderation process.
