### ISSUE TITLE
KeePass Plugin KeeAgent does not uninstall

### ISSUE THREAD

**Issue by ivkusan** [pauby/ChocoPackages#21]
When I try to uninstall KeePass Plugin KeeAgent, it returns an error:
```
keepass-plugin-keeagent v0.10.1.20180815
ERROR: Cannot bind argument to parameter 'Path' because it is null.
keepass-plugin-keeagent uninstall not successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass-plugin-keeagent\tools\chocolateyUninstall.ps1'.
 See log for details.
keepass-plugin-keeagent not uninstalled. An error occurred during uninstall:
 keepass-plugin-keeagent uninstall not successful.
```

[Debug log is here](https://gist.github.com/ivkusan/1d5ae699dbb42ce665ddb86d68cf5dad#file-chocolatey-log)

**Comment by pauby** [comment]
Thanks for your issue. I'll take a look.

**Comment by pauby** [comment]
I've opened this up for other to help. PR's welcome.

**Comment by pauby** [comment]
I can't reproduce this issue.

![image](https://user-images.githubusercontent.com/12760779/54497014-8b1ea080-48ed-11e9-8e75-2d382841a681.png)

If the file `KeeAgent_v0.10.1.20180815.zip` was removed before the uninstall then I believe this error will be thrown as it cannot find it. These [lines](https://gist.github.com/ivkusan/1d5ae699dbb42ce665ddb86d68cf5dad#file-chocolatey-log-L389-L390) indicate that `path` is null, `path` in this case being `KeeAgent_v0.10.1.20180815.zip` as seen at [this line of code](https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/UnInstall-ChocolateyZipPackage.ps1#L71)

@ivkusan Can you provide anymore information on this given the above?
