### ISSUE TITLE
Adobereader not up to date

### ISSUE THREAD

**Issue by chimmmpie** [pauby/ChocoPackages#210]
### Checklist

- [X] The package has been outdated for _at least_ 2 days.
- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] I have checked the **Version History** section of the package page and the new version is not listed, in any state.
- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

24.001.20615

### Download location

https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/continuous/dccontinuousmar2024qfe.html#dccontinuousmartwentytwentyfourqfe

### Package Page

https://community.chocolatey.org/packages/adobereader

**Comment by chimmmpie** [comment]
https://community.chocolatey.org/packages/adobereader/2024.1.20643

**Comment by pauby** [comment]
You ticked the box, but it's clear you haven't checked it.

![image](https://github.com/pauby/ChocoPackages/assets/12760779/43968ef5-058d-4b5d-8931-0b12abde2daa)

**Comment by chimmmpie** [comment]
My ticket is from 25 march
![image](https://github.com/pauby/ChocoPackages/assets/100216511/5bdfa556-e156-40c4-9d70-a7d41fc97519)
