### ISSUE TITLE
(admin center) - add PS5 as dependency

### ISSUE THREAD

**Issue by bcurran3** [pauby/ChocoPackages#22]
Thanks for packaging this!

"WMF (aka powershell) 5.1 needs to be installed on the machine" - please consider adding it as a dependency. (Yeah, I know it still won't pass the verifier as installing PS5 will require a reboot.)

**Comment by pauby** [comment]
Thanks for the suggestion. If you want to submit a PR for it I'll add it - if you do can you aslo add a note to the package description to say it's required / will be installed.

Thanks.
