### ISSUE TITLE
(adobereader) Not being updated

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#222]
## Expected Behaviour
The package should be querying the website and getting the latest package versions.

## Current Behaviour
The package is failing to update as the [Adobe web page is broken / very slow to browse](https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html), so the update script times out.

![image](https://github.com/pauby/ChocoPackages/assets/12760779/413e3a51-82be-40f1-a6eb-b79cde5d4686)

## Possible Solution
Switch to Evergreen.

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment

Happens locally and in AppVeyor.

**Comment by freaky-m0** [comment]
Would it be helpful if I update this manually for you? So you have "time" to fix your build problem and the choco package will be updated. There is a critical security issue in the old version and I think this should be pushed out quickly.

Should be just the version number & the checksums and links, or?

Thanks for your good work :)

**Comment by pauby** [comment]
Let me try and fix this later today. I have a way forward, but I just need to test it a lot to make sure I don't break anything.

If we are still ion the same situation tomorrow, I'll do the work manually and push it up.

**Comment by pauby** [comment]
I was ill yesterday so didn't get a chance to look at this. 

I have changed the version detection to use [Evergreen](https://github.com/pauby/ChocoPackages/commit/f06006c4b7281f5e66d9d0b4066d23f1f1927d61).

The MSP patch was used, as the MUI full version was only released periodically. However, if Evergreen is providing a full MUI version each time, I don't think we need the patch anymore. However, my goal here was to get the update script working and a new version published. I can look at this later when I have more versions, using Evergreen, approved (I can then see if the full MUI installer is being updated every time).

This latest version has just been pushed to the Chocolatey Community Repository. Once it's approved, I'll close this issue.

**Comment by pauby** [comment]
[This is now approved](https://community.chocolatey.org/packages/adobereader/2024.2.20759).
