### ISSUE TITLE
(wingetcreate) Outdated

### ISSUE THREAD

**Issue by devoptimate** [pauby/ChocoPackages#224]
### Checklist

- [X] The package has been outdated for _at least_ 2 days.
- [X] I have checked the [moderation queue](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) and no new version has been submitted (only visible when logged in), or a version has been submitted but has failed the automated checks.

- [X] I have checked the **Version History** section of the package page and the new version is not listed, in any state.
- [X] The new version is a stable release. Pre-release versions will not be added.
- [X] There are no existing [bug](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Abug) or [outdated](https://github.com/pauby/ChocoPackages/issues?q=is%3Aissue+is%3Aopen+label%3Aoutdated) issues.
- [X] The new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.6.1.0

### Download location

https://github.com/microsoft/winget-create/releases/tag/v1.6.1.0

### Package Page

https://community.chocolatey.org/packages/wingetcreate

**Comment by pauby** [comment]
The `<releaseNotes>` field content was causing the update script to fail. I've [removed it](https://github.com/pauby/ChocoPackages/commit/df105fc27c951ac48cf7c5233c8e77b5f64e252a) and a new version should be pushed shortly.

**Comment by pauby** [comment]
This has now been [submitted](https://community.chocolatey.org/packages/wingetcreate/1.6.1). Closing this issue.

**Comment by pauby** [comment]
Latest version, 1.6.1 has been approved.
