### ISSUE TITLE
(emacs.install) Cannot find file at c:\program files\... 

### ISSUE THREAD

**Issue by Gieted** [pauby/ChocoPackages#225]
### Checklist

- [X] I have checked for similar opened and closed issues.
- [X] The issue title is in the format `(<PACKAGENAME>) <ISSUE SUMMARY>`.

### Chocolatey Version

2.3.0

### Chocolatey License

None

### Package Version

29.3.0 

### Current Behaviour

After installation running `emacs` shows:
```
Cannot find file at 'c:\program files\emacs\emacs-29.3\bin\emacs.exe' (c:\program files\emacs\emacs-29.3\bin\emacs.exe). This usually indicates a missing or moved file.
```

probably because incorrect escaping of "program files"

### Expected Behaviour

Emacs should launch

### Steps To Reproduce

1. Install package
2. Run `emacs` in the terminal

### Environment

```markdown
- Operating System (run `[System.Environment]::OSVersion.ToString()` in a PowerShell session): Microsoft Windows NT 10.0.22631.0
- PowerShell Version (run `$PSVersionTable` in a PowerShell session): 5.1.22621.3672
- Shell: Powershell
```

### Chocolatey Log

```shell
-
```

**Comment by pauby** [comment]
Looking at this now this is because the emacs installer is creating a folder called `emacs-29.3_2` for some reason. So the shims are not found (as the fo9lder it's looking for is `emacs-29.3`.

**Comment by pauby** [comment]
Version 29.4.0 of `emacs.install` appears to work correctly so I'm going to assume this is an emacs installer mistake.

I'll go ahead and close this now.
