### ISSUE TITLE
(keepass.portable) Option for custom unzip location

### ISSUE THREAD

**Issue by SharpSeeEr** [pauby/ChocoPackages#25]
Would you be open to adding a package parameter to the keepass.portable package to allow unzipping to a custom location?  I have always kept my keepass portable on my OneDrive, making it easy to get to my passwords and the program from other computers.
If so, I'd be more than happy to make the changes and send you a pull request. Thanks!

**Comment by pauby** [comment]
@SharpSeeEr Absolutely. If you put a PR in and everything works I'll happily merge it.

**Comment by SharpSeeEr** [comment]
Pull request sent.  https://github.com/pauby/ChocoPackages/pull/27

**Comment by pauby** [comment]
PR #27 submitted for this.
