### ISSUE TITLE
keepass.portable - Configuration does not save

### ISSUE THREAD

**Issue by saschabrunner** [pauby/ChocoPackages#31]
keepass.portable seems to save its configuration next to its executable (inside "KeePass.config.xml"). However by default, it has no permission to write to that file (unless you run it as Administrator).

To fix it on my machine, I had to give the whole "tools" folder permissions (see attached screenshot).

![image](https://user-images.githubusercontent.com/13722407/54482950-4dfdd400-4843-11e9-9982-b2327b02c9f7.png)

**Comment by pauby** [comment]
@saschabrunner Thanks for raising this issue. If you can help then a PR is very welcome.

**Comment by pauby** [comment]
I've updated the package to extract to the tools folder (c:\tools by default). This folder has permissions for non-admin users.

I haven't done a package fix version of this to keep `keepass`, `keepass.install` and `keepass.portable` all with the same version number but the next `keepass.portable` version to be released will be updated with these changes.
