### ISSUE TITLE
Microsoft OneNote locale always en-US

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [pauby/ChocoPackages#40]
There are language specific versions available. Is there a way to add a switch for the locale (or a way to download the version for the installed Windows language)?

**Comment by pauby** [comment]
I don't know anything about the additional languages but happy to provide support, if possible, if you point me to where they are available and how?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
current installer english only: 
https://www.onenote.com/download/win32/x64/en-US/ from installer script
if you know how to reliably get windows language from script? i can point you to more languages available from country codes installers:
https://www.onenote.com/download/win32/x64/ru-RU/
https://www.onenote.com/download/win32/x64/de-DE/
https://www.onenote.com/download/win32/x64/it-IT/
https://www.onenote.com/Download/win32/x64/pt-BR/
https://www.onenote.com/Download/win32/x64/tr-TR/
https://www.onenote.com/Download/win32/x64/sv-SE/
https://www.onenote.com/download/win32/x64/es-ES/
https://www.onenote.com/download/win32/x64/ja-JP/
https://www.onenote.com/Download/win32/x64/fr-FR/
https://www.onenote.com/download/win32/x64/vi-VN/
https://www.onenote.com/Download/win32/x64/zh-CN/
https://www.onenote.com/download/win32/x64/pl-PL/
https://www.onenote.com/Download/win32/x64/ko-KR/

both x86 x64 available each

and so on, not complete

**Comment by pauby** [comment]
Okay, that's quite a bit of work there so I'm going to open it up for others to pickup as I won't get the time for it soon.
