### ISSUE TITLE
invokebuild - Duplicate package

### ISSUE THREAD

**Issue by gep13** [pauby/ChocoPackages#44]
It has been pointed out that your package for [invokebuild](https://chocolatey.org/packages/invokebuild) is actually a duplicate of the existing package [invoke-build](https://chocolatey.org/packages/invoke-build).  This must have been missed during the initial review/approval of the package.

Since the existing invoke-build package is named in accordance with the actual underlying software, I would suggest that the invokebuild be moved through the [deprecation process](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package), as it is a duplicate.

**Comment by pauby** [comment]
The software is actually called `invokebuild` and not `invoke-build` (see [PowerShell Gallery](https://www.powershellgallery.com/packages?q=invokebuild)) so the package is named correctly as it's based on the software. Although nightroman does talk about the project being `Invoke-Build` in the [README](https://github.com/nightroman/Invoke-Build/blob/master/README.md). My intention is not to create a duplicate package (I have enough packages to maintain without adding another) but ths is likely why it was missed (it's been over a year so I'm obviously guessing).

I have been slowly adding the ability to support both Core and Desktop PowerShell for all my PowerShell Chocolatey packages (see the [description and code](https://github.com/pauby/chocopackages/tree/master/automatic/pshtml.powershell) for `pshtml.powershell` as an example) and I intended to add this to InvokeBuild. This is important to me and the community to allow both.

However for ease I will raise an issue at the repo for Invoke-Build to discuss adding that functionality.

**Comment by gep13** [comment]
@pauby I think that there is still work to be done here, right?

**Comment by pauby** [comment]
@gep13 There is. I've reopened it.

**Comment by pauby** [comment]
The other issue at https://github.com/majkinetor/au-packages/issues/123 has been closed so there is nothing more to be done here. That package still doesn't have the ability to install in PowerShell Core.
