### ISSUE TITLE
Taking over the KeeTrayTOTP plugin for KeePass

### ISSUE THREAD

**Issue by ebekker** [pauby/ChocoPackages#45]
I recently tried to [contribute a PR](https://github.com/dtgm/chocolatey-packages/pull/471) to the original dtgm repo for an update to the KeeTrayTOTP plugin for KeePass, but found out that repo is no longer being maintained.  As suggested by @gep13, since you have taken over maintenance of the main KeePass choco package and a few of the plugins already, I'm inquiring if you would be willing to adopt one more package?

I can submit a PR to add that plugin to your repo.  It looks like your setup is a bit different than what was in the dtgm repo, so I'll adjust accordingly if you agree?

**Comment by pauby** [comment]
I'm happy to take on the package if you want to submit a PR.

**Comment by ebekker** [comment]
Sorry, I haven't had time to look into refactoring the [original PR](https://github.com/dtgm/chocolatey-packages/pull/471) to make it compatible with this repo (too much happening this time of year).

I'll let stale bot close this out for now, and will reopen later on.

**Comment by pauby** [comment]
I've just looked at this and the [last version of the plugin](https://sourceforge.net/projects/traytotp-kp2/) available is actually the latest version on the [package page](https://chocolatey.org/packages/keepass-plugin-traytotp/2.0.0.5)

There is a fork at https://github.com/KeeTrayTOTP/KeeTrayTOTP which I'm going to look to add.

**Comment by pauby** [comment]
This was added at https://github.com/pauby/ChocoPackages/commit/122af24a85da7e5b724e930549bb39bb0c198ceb and the new package is [here](https://chocolatey.org/packages/keepass-plugin-keetraytotp).

**Comment by ebekker** [comment]
Awesome, thanks!
