### ISSUE TITLE
Doesn't handle new major versions properly

### ISSUE THREAD

**Issue by bc3tech** [pauby/ChocoPackages#48]
When Snagit 2020 came out, a `choco upgrade` from snagit 2019 results in a side-by-side install of 2019 and 2020. We should uninstall previous major version before installing new ones.

**Comment by pauby** [comment]
This is the behaviour by the installer but I agree it's not ideal. PR's welcome to change the package to compensate.

**Comment by bc3tech** [comment]
i'm not well versed in the usage of `chocolateybeforemodify.ps1` but it seems like that's exactly what could be used to solve this. otherwise i'd happily submit a pr.
