### ISSUE TITLE
Uninstall of 2019.1.3 auto-uninstalls Beyond Compare 4

### ISSUE THREAD

**Issue by bc3tech** [pauby/ChocoPackages#49]
I had BC4 and SnagIt 2019.1.3 on my system. When I did `cuninst snagit -y` it uninstalled Beyond Compare 4 and not SnagIt 2019.

**Comment by pauby** [comment]
I can't reproduce this I'm afraid.

Software installed.

<img width="655" alt="WindowsSandbox_2019-12-16_20-16-30" src="https://user-images.githubusercontent.com/12760779/70940164-a6b40480-2041-11ea-954f-37223163d238.png">

After uninstall - `choco uninstall snagit`:

<img width="639" alt="WindowsSandbox_2019-12-16_20-19-05" src="https://user-images.githubusercontent.com/12760779/70940183-b5022080-2041-11ea-95f7-4d1d2b1dcaef.png">
