### ISSUE TITLE
hugo package not automatically updating x86 version

### ISSUE THREAD

**Issue by mikeee** [pauby/ChocoPackages#53]
This issue was originally highlighted in the main hugo repo:
https://github.com/gohugoio/hugo/issues/7186

The x86 version of hugo is not packaged and is reproducible when attempting to install hugo x86 using the `-forcex86` flag, the installed version of hugo is v0.51 which was the one last packaged.

**Comment by pauby** [comment]
It's clear that I was only ever publishing the x64 version of hugo but having that `url` property int he `chocolateyInstall.ps1` meant that Chocolatey thought there was also an x86 version. 

What I am a little disappointed in is that 50 version of Hugo has gone by and nobody mentioned it. But it does appear from the conversation you linked to that it was known about 😢 

Thank you very much for the PR and for fixing this. From the next version this will take effect. Also added a note around the broken x86 version at https://github.com/pauby/ChocoPackages/commit/9c223daed2baf605e94fbc813fb8e72b280f93e4

**Comment by pauby** [comment]
Just an update to let you know that Hugo 0.71.1 has just been approved with the changes in it!
