### ISSUE TITLE
Autoupdater seems to be picking up pre-release version of gh

### ISSUE THREAD

**Issue by douglaswth** [pauby/ChocoPackages#56]
I think I noticed this with another version, but it definitely happened this time. The current package says it is 0.9.0, but when running the command:

```
gh version 0.9.0-pre (2020-05-26)
https://github.com/cli/cli/releases/tag/v0.9.0-pre


A new release of gh is available: 0.9.0-pre → v0.9.0
https://github.com/cli/cli/releases/tag/v0.9.0
```

**Comment by pauby** [comment]
I've had a look at the code and I think what has happened is that the version of gh that was released as version 0.9.0 was still labelled with `-pre`.

If you have a look at `[update.ps1](https://github.com/pauby/ChocoPackages/blob/master/automatic/gh/update.ps1)` it looks for the following regular expression as a link `/download/v(?<version>[\d\.]+)/gh_[\d\.]+_windows_amd64.msi`. If you have a look at the files released as part of 0.9.0-pre you can see there is a `zip` and a `.tar.gz` which don't match that regex (there is not `gh_0.9.0_windows_amd64.msi` file which is what is in the package so it couldn't have taken it from there.

If you look at the [files](https://chocolatey.org/packages/gh/0.9.0#files) link on the Package Page the installer is named `gh_0.9.0_windows_amd64.msi` which is the name used for the 0.9.0 release.

I'm going to close this issue but we can always reopen it if need be.
