### ISSUE TITLE
Update status gist outdated

### ISSUE THREAD

**Issue by OlafHaag** [pauby/ChocoPackages#57]
Hey! This is just a minor thing. The Update status link in the README leads to a gist that is over 2 years old.
Maybe the environment variable for the gist_id isn't set correctly in appveyor, or so.

**Comment by pauby** [comment]
Thanks for pointing that out @OlafHaag. I've just removed in [this commit](https://github.com/pauby/ChocoPackages/commit/f42e2f0ba4cf284f6ce9a7f5621b050c00a0df31).
