### ISSUE TITLE
[gh] PATH is not updated, when installing GitHub CLI 0.10.0 

### ISSUE THREAD

**Issue by safor** [pauby/ChocoPackages#60]
After installation of [GitHub CLI 0.10.0](https://chocolatey.org/packages/gh/0.10.0) on Windows 10, it is not possible to run `gh` application. Reason: the PATH environment variable doesn't have the path to the place, when `gh` is installed.

The application was installed to `C:\Program Files (x86)\GitHub CLI\`
OS version: Windows 10 Pro version 2004 (OS Build 19041.329)
Chocolatey version: 0.10.15

Attempts to fix the issue:
* run the force installs of the chocolatey package from the elevated PowerShell - didn't help
* found the GitHub CLI among the installed programs under the Windows Setting, clicked "Modify" and "Repair" button - the MSI package run and updated the PATH environment variable.

**Comment by pauby** [comment]
The Chocolatey package simply installs the MSI silently. The responsibility to update the path lies with the installer and not the package or Chocolatey. What you may find is that the path is updated by the installer but doesn't update the console session. The `refreshenv` Chocolatey command can do that for you.

I've just tested it in a Windows 10 virtual machine and it works fine after I run the `refreshenv` command:

![image](https://user-images.githubusercontent.com/12760779/85568629-c0a25580-b629-11ea-9bf5-2decb8f29b6c.png)

**Comment by safor** [comment]
Agree, the issue is not in the package.

Here are more details about what went wrong on my side:
* I was installing the GitHub CLI from an elevated PowerShell session
* After `choco install gh` finished, the `C:\Program Files (x86)\GitHub CLI\` was appended to the PATH environment variable of the Administrator user (not my local user)
* Being in the same elevated PowerShell session, when I run `refreshenv`, it refreshed environment variables for cmd.exe (the same output message we can the on the screenshot attached to the previous message), but `$env:PATH` stayed unchanged.

It is why I could not run `gh`.

Now, if I want to run `gh` under my local user, I have to update its PATH manually. Not nice. Anyway, this issue should be closed. Thank you!

**Comment by pauby** [comment]
If you don't have a PowerShell profile setup _before_ you install Chocolatey it won't add the Chocolatey helpers to the profile for you. So, in PowerShell, the `refreshenv` command won't work but it will work in CMD.

That is likely why the `refreshenv` command didn't refresh your PowerShell session.
