### ISSUE TITLE
Snagit Hash issue v2020.1.3 

### ISSUE THREAD

**Issue by peterbarendse** [pauby/ChocoPackages#62]
Chocolatey package Snagit has has issues.

snagit v2020.1.3 [Approved]
snagit package files install completed. Performing other installation steps.
Downloading snagit 64 bit
  from 'https://download.techsmith.com/snagit/releases/2013/snagit.msi'
Progress: 100% - Completed download of 'snagit.msi' (326.86 MB).
Download of 'snagit.msi' (326.86 MB) completed.

Error - hashes do not match. Actual value was '02ADD83F068FEA103B8324B7DB7864070E0A50858C7254476950C2446EC85EA5'.

**Comment by pauby** [comment]
Thanks for reporting this. I simply haven't had time to update it as yet. I'm happy to accept a PR otherwise leave it with me!

**Comment by virtualex-itv** [comment]
@pauby - PR submitted ([#63](https://github.com/pauby/ChocoPackages/pull/63))

**Comment by pauby** [comment]
Fixed via #63
