### ISSUE TITLE
Keepass-plugin Readable Passphrase update error

### ISSUE THREAD

**Issue by Wambou** [pauby/ChocoPackages#65]
Hi,

I am using Chocolatey and really like the Readable Passphrase Keepass plugin.
I noticed that the latest version is not properly packaged and scripts still refer to version 1.1.1.

I made two pull-requests because I was not sure how to properly update things so that automatic packaging kicks in properly.

I hope this helps.

**Comment by pauby** [comment]
This is now available at https://github.com/pauby/ChocoPackages/commit/2ba351a8cbc11fe5d8b4d0632d78752e2f24d3e3
