### ISSUE TITLE
Virtualbox Guest Extensions has wrong license linked.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [pauby/ChocoPackages#74]
The `virtualbox-guest-additions-guest.install` package has the wrong license linked. 

It is linking to the [Oracle Personal Use and Evaluation License](https://www.virtualbox.org/wiki/VirtualBox_PUEL), while it actually should be linking to the [GPL v2.0](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) license. This is according to the [Licensing FAQ](https://www.virtualbox.org/wiki/Licensing_FAQ).

Also, because the ISO is only about ~50mb, and the GPL allows redistribution of binaries, I believe this package is embeddable.

**Comment by pauby** [comment]
Thanks for raising this. It's been fixed at https://github.com/pauby/ChocoPackages/commit/ed8daf5d9b31a23c8cc8b4416b12cfb4aa13a785 and will be pushed with the next version.

**Comment by TheCakeIsNaOH** [comment]
Thanks for the fix.
