### ISSUE TITLE
KeePass Plugin EnhancedEntryView is outdated

### ISSUE THREAD

**Issue by smainz** [pauby/ChocoPackages#75]
Hi,

this is outdated: **KeePass Plugin EnhancedEntryView**

Current version is 2.3.1 (https://sourceforge.net/projects/kpenhentryview/files/v2.3.1/) 
what is available on chocolatey is 2.1.4.

Could you please update?

If you need help, please drop me a note on what and how.

Thanks

**Comment by pauby** [comment]
This has been updated and pushed to the [Community Repository](https://chocolatey.org/packages/keepass-plugin-enhancedentryview/2.4.1).
