### ISSUE TITLE
(snagit) "nodesktopshortcut" param not working

### ISSUE THREAD

**Issue by virtualex-itv** [pauby/ChocoPackages#79]
![2021-03-18_13-22-32](https://user-images.githubusercontent.com/12056704/111669831-90b96480-87ed-11eb-97f0-c149728debd7.png)

**Comment by virtualex-itv** [comment]
looks like the `TSC_DESKTOP_LINK` property was removed...
![2021-03-19_9-26-15](https://user-images.githubusercontent.com/12056704/111787974-f82aef00-8895-11eb-8196-8b22bfe90dae.png)

**Comment by pauby** [comment]
As an update to this I'm having to rewrite the Snagit package entirely due to a change in dependencies and the installer. Bear with me.

**Comment by pauby** [comment]
This was fixed over at #127
