### ISSUE TITLE
(teamviewer) Add 64-bit version

### ISSUE THREAD

**Issue by HamsterHam88** [pauby/ChocoPackages#84]
Hi

Please can you add the 64-bit version to the package.

Thanks

**Comment by pauby** [comment]
Thanks for the issue. I'll work on this as soon as I can.

**Comment by ComFreek** [comment]
It seems that the 32-bit version of Teamviewer contains some critical bugs.
Namely, today I've spent 2 hours figuring out why I couldn't connect to a certain Teamviewer instance only to eventually find out that the 32-bit version was the culprit. After installing the 64-bit one manually everything was fine.

**Comment by pauby** [comment]
This was fixed in #99
