### ISSUE TITLE
keepass-plugin-rulebuilder is outdated

### ISSUE THREAD

**Issue by brogers5** [pauby/ChocoPackages#86]
Version 3.0 was released on April 20th:
https://github.com/ihanson/KeePass-Rule-Builder/releases/tag/v3.0

I see that an updated package was previously submitted here:
https://community.chocolatey.org/packages/keepass-plugin-rulebuilder/3.0

However, the updated package had failed automated testing and was ultimately rejected since the failure wasn't resolved in time.

**Comment by brogers5** [comment]
This is still problematic, albeit not necessarily requiring further action at this time. v3.1 has since been released, and a package automatically created for it, pending moderator approval since since June 7th.

https://community.chocolatey.org/packages/keepass-plugin-rulebuilder/3.1

**Comment by pauby** [comment]
The original issue was for the package being outdated. As an updated package has been submitted and is awaiting human moderation this issue is resolved.
