### ISSUE TITLE
(streamdeck) Package outdated

### ISSUE THREAD

**Issue by DragRedSim** [pauby/ChocoPackages#90]
As per title; newest version is 5.1.2.14743.

**Comment by pauby** [comment]
Thanks for letting me know about this. I had a lot of trouble in the past from the Streamdeck installer itself so I'm hoping this isn't another issue with trying to find the updated software.

**Comment by psjamesp** [comment]
The newest version is now 5.1.4

**Comment by abellmann** [comment]
the newest version is now 5.2.0

**Comment by pauby** [comment]
@virtualex-itv I've gone through the changes you made to the `snagit` package and there wasn't anything in there that would have changed the behaviour of the update script. I've moved the changes to Streamdeck into their own [branch](https://github.com/pauby/ChocoPackages/tree/fix/streamdeck).

My assumption was that the update was somehow broken and _assumed_ it was on Elgato's end. The Streamdeck MSI had been broken in the past so I don't have a lot of faith in Elgato getting things right.

However, the update script as it stands right now works when running locally. But it doesn't work in AppVeyor. All that is shown in the logs is `streamdeck has no updates`. 

When you log into the AppVeyor server and browse to the releases page]('https://help.elgato.com/hc/en-us/articles/360028242631-Elgato-Stream-Deck-Software-Release-Notes) it works fine (using Microsoft Edge). If you run the update script from an elevated command line, this is what you get:

```
PS C:\projects\chocopackages\automatic\streamdeck> .\update.ps1
streamdeck - checking updates using capu version 0.1.1
au_GetLatest failed
The remote server returned an error: (403) Forbidden.
At C:\projects\chocopackages\capu\capu.psm1:984 char:9
+         throw "au_GetLatest failed`n$_"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (au_GetLatest fa...403) Forbidden.:String) [], RuntimeException
    + FullyQualifiedErrorId : au_GetLatest failed
The remote server returned an error: (403) Forbidden.

PS C:\projects\chocopackages\automatic\streamdeck> $releases    = 'https://help.elgato.com/hc/en-us/articles/36002824263
1-Elgato-Stream-Deck-Software-Release-Notes'
PS C:\projects\chocopackages\automatic\streamdeck> Invoke-WebRequest -Uri $releases -UseBasicParsing -UserAgent [Microso
ft.PowerShell.Commands.PSUserAgent]::FireFox
Invoke-WebRequest : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Invoke-WebRequest -Uri $releases -UseBasicParsing -UserAgent [Microso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\projects\chocopackages\automatic\streamdeck> Invoke-WebRequest -Uri $releases -UserAgent [Microsoft.PowerShell.Com
mands.PSUserAgent]::FireFox
Invoke-WebRequest : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Invoke-WebRequest -Uri $releases -UserAgent [Microsoft.PowerShell.Com ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

The important bit is:

```
The remote server returned an error: (403) Forbidden.
```

Bearing in mind this _used_ to work just fine (the last successful update is 4.7.z) so Elgato have changed _something_. This is going to take a little while longer to figure out.

**Comment by pauby** [comment]
This has been fixed in [this commit](https://github.com/pauby/ChocoPackages/commit/504beb4bf684d672e431c82dcf03c496fad401b9).
