### ISSUE TITLE
(camtasia) package doesn't uninstall old version during an upgrade. 

### ISSUE THREAD

**Issue by algazod** [pauby/ChocoPackages#92]
If you upgrade camtasia from 2020 version to a 2021 in chocolatey/lib the new package (2021), but in reality you have all the software installed! I fixed using chocolateymodify.ps1. Pls take a look :)
PS: Last package update 26/08 seems no longer in automatically update.

**Comment by pauby** [comment]
This isn't a package issue. It's an installer issue.

But I'm not so sure it's an issue. If you download and install Camtasia 2021, it will leave the Camtasia 2020 installed. Note that the Chocolatey package is upgraded to 2021 though. So the Camtasia installer doesn't uninstall the older version. It actually never has. Snagit (also from Techsmith who author Camtasia) does _exactly_ the same thing.

So I'm not going to modify the package to uninstall the previous version. That would be unexpected behaviour IMO (ie. it's different from what the installer does). However, I think the description for Camtasia (and Snagit) should be updated to say that older major versions are not uninstalled.

**Comment by pauby** [comment]
This was fixed on [this commit](https://github.com/pauby/ChocoPackages/commit/818c3f27ad449d663aa4c13228ab680ab8082361) for camtasia and [this commit](https://github.com/pauby/ChocoPackages/commit/5a3f3d3229314bf3cdfe71ab6306220c1ff0633a) for snagit.
