### ISSUE TITLE
KeePass Plugin KeeTrayTOTP 0.108.0

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [pauby/ChocoPackages#93]
KeePass Plugin KeeTrayTOTP

v0.108.0

It is not an upgraded version. It is actually: **0.107.0**

https://community.chocolatey.org/packages/keepass-plugin-keetraytotp#versionhistory

v0.108.0 package version
https://github.com/pauby/ChocoPackages/blob/master/automatic/keepass-plugin-keetraytotp/tools/KeeTrayTOTP.plgx

original v0.108.0 plugin version
https://github.com/KeeTrayTOTP/KeeTrayTOTP/releases/download/v0.108.0/KeeTrayTOTP.plgx

KeeTrayTOTP
- https://github.com/KeeTrayTOTP/KeeTrayTOTP/pull/252

**Comment by pauby** [comment]
The version scheme that is used is that shown in the GitHub releases page. Why was a new release produced when the release version was not incremented?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
The plugin file from keepass-plugin-keetraytotp-0.108.0 contains 0.107.0 version of Plugin.

https://github.com/pauby/ChocoPackages/blob/master/automatic/keepass-plugin-keetraytotp/tools/KeeTrayTOTP.plgx is outdated

**Comment by pauby** [comment]
Okay. I see what you're asking. That file is the file stored in GitHub but is not the file that is used in the package. The file used in the package is downloaded at the time a new package is created and bundled in there. Please see the package itself. Please also see the checksums below:

![image](https://user-images.githubusercontent.com/12760779/144291221-1b226b2e-10e3-458e-ae28-69f308e9a2b5.png)

The one on the left is from the package. The one on the right was downloaded from GitHub releases.

I've removed the word fake from your messages above. It has connotations that are not helpful here.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> 
> I've removed the word 'fake' from your messages above. It has connotations that are not helpful here.

Yes, well, don't get me wrong. I'm not trying to accuse you of faking. I just recognized the wrong version information. Glad maintainers care about plugins.

**Comment by pauby** [comment]
Nope, I got it. Just when people see that word 'fake' they think people are up to no good 😄 I've removed the binary file from the package's directory (it shouldn't have been there in the first place, so I've also updated `.gitignore`).
