### ISSUE TITLE
(sharex) Package is outdated

### ISSUE THREAD

**Issue by dss539** [pauby/ChocoPackages#94]
The ShareX package hasn't been updated on chocolately.org since September 10.  

I see you fixed some things since then, but it looks like the automatic deployment didn't trigger.

**Comment by pauby** [comment]
Thanks for letting me know. I'll be taking a look at all of these issues over the Xmas period so expect some updates then.

**Comment by dss539** [comment]
Thanks for your work on this. It's much appreciated.

**Comment by pauby** [comment]
It looks like the dependencies on this package are deprecated. Looks like `netfx-4.7.2` skills be used instead.

**Comment by pauby** [comment]
According to the [changelog](https://github.com/pauby/ChocoPackages/commit/5a3f3d3229314bf3cdfe71ab6306220c1ff0633a), .NET 4.8 is required.

**Comment by pauby** [comment]
@dss539 Thanks for raising the issue and apologies for taking so long to get to it. The dependency has been fixed [here](https://github.com/pauby/ChocoPackages/commit/2abb8e4067a9daeca69a57f104c80a5a68cf1e75).

**Comment by dss539** [comment]
Thanks!
No worries on the delay.
