### ISSUE TITLE
(teamviewer) Add 64 bit support

### ISSUE THREAD

**Issue by pauby** [pauby/ChocoPackages#98]
Teamviewer is using the x86 as that is all that was available at the time the package was created. x64 binaries are now available and should be added to the package.

See [Disqus comment](https://community.chocolatey.org/packages/teamviewer#comment-5680782675)

**Comment by koitsu** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue will be closed in 14 days if it continues to be inactive.

Yes, automated bot-thing, it is still relevant.

**Comment by pauby** [comment]
This was completed in #99.
